/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../hooks/useLocationDistance`; params?: Router.UnknownInputParams; } | { pathname: `/../components/GlobalCallNotification`; params?: Router.UnknownInputParams; } | { pathname: `/../components/games/DoodleGame`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/hub` | `/hub`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/gallery` | `/gallery`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/games` | `/games`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/letters` | `/letters`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/music` | `/music`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/surprises` | `/surprises`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../hooks/useLocationDistance`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/GlobalCallNotification`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/games/DoodleGame`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/hub` | `/hub`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/gallery` | `/gallery`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/games` | `/games`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/letters` | `/letters`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/music` | `/music`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/surprises` | `/surprises`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../hooks/useLocationDistance${`?${string}` | `#${string}` | ''}` | `/../components/GlobalCallNotification${`?${string}` | `#${string}` | ''}` | `/../components/games/DoodleGame${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calendar${`?${string}` | `#${string}` | ''}` | `/calendar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/hub${`?${string}` | `#${string}` | ''}` | `/hub${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/gallery${`?${string}` | `#${string}` | ''}` | `/gallery${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/games${`?${string}` | `#${string}` | ''}` | `/games${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/letters${`?${string}` | `#${string}` | ''}` | `/letters${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/music${`?${string}` | `#${string}` | ''}` | `/music${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/surprises${`?${string}` | `#${string}` | ''}` | `/surprises${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../hooks/useLocationDistance`; params?: Router.UnknownInputParams; } | { pathname: `/../components/GlobalCallNotification`; params?: Router.UnknownInputParams; } | { pathname: `/../components/games/DoodleGame`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/hub` | `/hub`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/gallery` | `/gallery`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/games` | `/games`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/letters` | `/letters`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/music` | `/music`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/surprises` | `/surprises`; params?: Router.UnknownInputParams; };
    }
  }
}
